Second: 0
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_Id_Generator::generateId(s)] __end__ Total: 0 milliseconds.
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __start__
[ 2064 1472][17 Oct 18:37:28][XmlWrapper] XmlDocument::XmlDocument: inside
[ 2064 1472][17 Oct 18:37:28][XmlWrapper] XmlDocument::SaveString: inside
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [DEBUG] [Diagnostic_EventReporter::_report_event(s)] new event after removing 0d0a: 

<OBJECT name="helpdesk event" type="DiagnosticHelpdeskEventData">

  <OBJECT name="idD" type="Diagnostic_RecordId">
    <Field name="timeStampD" value="1666049848"></Field>
    <Field name="serialD" value="0"></Field>
  </OBJECT>

  <Field name="dataTypeD" value="1"></Field>

  <Field name="dataDisplayTypeD" value="0"></Field>

  <Field name="userNameD" value=""></Field>

  <Field name="siteNameD" value=""></Field>

  <Field name="gwNameD" value=""></Field>

  <Field name="gwIPD" value=""></Field>

  <Field name="severityLevelD" value="1"></Field>

  <Field name="dataD" value="Service was started"></Field>

  <Field name="helpdeskRecordTypeD" value="-1"></Field>

</OBJECT>

[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __start__
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_eventLogHandler::Diagnostic_eventLogHandler::writeEventToLog(s)] __end__ Total: 1 milliseconds.
[ 2064 1472][17 Oct 18:37:28][TR_CONN_MANAGER] diagnostic_reporter: entering...
[ 2064 1472][17 Oct 18:37:28][TR_CONN_MANAGER] TR_CONN_MANAGER::CreateAndSendNotification: TrEventManager is not ready yet - ignore this notification - return
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::_report_event(s)] __end__ Total: 1 milliseconds.
[ 2064 1472][17 Oct 18:37:28][DIAGNOSTIC] [COVERAGE] [Diagnostic_EventReporter::report_helpdesk_event_1(s)] __end__ Total: 1 milliseconds.
[ 2064 1472][17 Oct 18:37:28][TracService] Software\CheckPoint\TRAC\5.0 exists - no need to backup
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::create: __start__ 18:37:28.316
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::ConfigurationManager: __start__ 18:37:28.316
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::init(): __start__ 18:37:28.316
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::load(): __start__ 18:37:28.316
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams()
[ 2064 1472][17 Oct 18:37:28][FileManager] FileManager::openFile: file "trac.defaults" does not exist
[ 2064 1472][17 Oct 18:37:28][FileManager] FileManager::readFile: error occured while opening the file "trac.defaults"
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::loadDefaultParams() error reading trac.defaults file in ConfigurationManager::loadDefaultParams()
[ 2064 1472][17 Oct 18:37:28][RaisException] RaisException::BaseException::BaseException: error code = 11, error message = error reading file in ConfigurationManager::loadDefaultParams(), file name =ConfigurationManager.cpp, line number = 1369
[ 2064 1472][17 Oct 18:37:28][CONFIG_MANAGER] ConfigurationManager::load(): __end__ 18:37:28.316. Total time - 0 milliseconds
[ 2064 1472][